
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND_OP LPAREN OR_OP RPAREN TERMexpression : expression OR_OP expressionexpression : expression AND_OP expressionexpression : factorfactor : LPAREN expression RPARENfactor : TERM'
    
_lr_action_items = {'LPAREN':([0,3,5,6,],[3,3,3,3,]),'TERM':([0,3,5,6,],[4,4,4,4,]),'$end':([1,2,4,8,9,10,],[0,-3,-5,-1,-2,-4,]),'OR_OP':([1,2,4,7,8,9,10,],[5,-3,-5,5,5,5,-4,]),'AND_OP':([1,2,4,7,8,9,10,],[6,-3,-5,6,6,6,-4,]),'RPAREN':([2,4,7,8,9,10,],[-3,-5,10,-1,-2,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,5,6,],[1,7,8,9,]),'factor':([0,3,5,6,],[2,2,2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression OR_OP expression','expression',3,'p_expression_or','parser.py',32),
  ('expression -> expression AND_OP expression','expression',3,'p_expression_and','parser.py',37),
  ('expression -> factor','expression',1,'p_expression_unary','parser.py',43),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',48),
  ('factor -> TERM','factor',1,'p_factor_term','parser.py',52),
]
